version: '3.8'

services:
  postgres:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  postgres_data: 